### ISSUE TITLE
Move to rust-ndarray organization?

### ISSUE THREAD

**Issue by termoshtt** [rust-ndarray/ndarray-linalg#126]
Related to https://github.com/rust-ndarray/ndarray/issues/424

**Comment by termoshtt** [comment]
I create a [rust-math](https://github.com/rust-math) to manage my rust crates related to scientific computing, and move this crate there.

**Comment by LukeMathWalker** [comment]
I think it would make sense to move it to `rust-ndarray`.
It would increase the potential size for the pool of maintainers, giving out a stronger signal that it's a project meant to stay.

Furthermore, `ndarray-linalg` is de facto the only maintained crate for linear algebra that tightly integrate with `ndarray`: the latest release of `linxal` is two years old.
The value of `ndarray` itself would be greatly diminished if this crate were to be abandoned.

What are your thoughts? @bluss @jturner314

**Comment by jturner314** [comment]
Moving `ndarray-linalg` to the `rust-ndarray` organization sounds good to me. It is a pretty essential crate for `ndarray`. It looks like @termoshtt can transfer the repo to `rust-ndarray` by following [this procedure](https://help.github.com/en/articles/transferring-a-repository#transferring-a-repository-owned-by-your-organization). I'll then accept the transfer, make sure @termoshtt still has full permissions for `ndarray-linalg`, and we should be done.

@termoshtt Would you like to add one or both of us as a second "owner" of `ndarray-linalg` on crates.io? That would be fine with me and would help provide redundancy, but if you'd like to retain sole ownership, that's fine too.

**Comment by termoshtt** [comment]
> Would you like to add one or both of us as a second "owner" of ndarray-linalg on crates.io? 
> That would be fine with me and would help provide redundancy

I think some member of rust-ndarray should be owner of this crate after transferred.

**Comment by LukeMathWalker** [comment]
> > Would you like to add one or both of us as a second "owner" of ndarray-linalg on crates.io?
> > That would be fine with me and would help provide redundancy
> 
> I think some member of rust-ndarray should be owner of this crate after transferred.

I agree - the whole point of having an organization is to be able to step in and keep developing the projects of the organization even if the main maintainer does not want to or is not able to keep doing it.

**Comment by termoshtt** [comment]
I try to transfer

![image](https://user-images.githubusercontent.com/1238153/57190557-64c4cb00-6f56-11e9-901e-8898e55c47dc.png)

maybe some notification goes to @jturner314 ?

**Comment by jturner314** [comment]
Huh, according to GitHub's documentation, I would think that I would have received an email notification to accept the transfer (the docs say "When the current owner initiates the transfer, the new owner will receive an email giving the option to accept or reject the transfer. If the new owner doesn't accept the transfer within one day, it won't complete."), but I didn't receive any such email.

@termoshtt I've invited you to be a member of the `rust-ndarray` organization. If you accept the invitation, you should have the necessary permissions to create repositories in `rust-ndarray`.

**Comment by termoshtt** [comment]
Thanks! and transfer is done.

**Comment by jturner314** [comment]
Great! I've given you admin permissions for `rust-ndarray/ndarray-linalg`. The only remaining piece is to add one or both of us as owners on crates.io.

**Comment by termoshtt** [comment]
I've sent invitations to both.

**Comment by LukeMathWalker** [comment]
Accepted @termoshtt.

**Comment by jturner314** [comment]
I've accepted as well. I think we're done now!
