### ISSUE TITLE
You code does not work on mac os

### ISSUE THREAD

**Issue by davidmontgom** [rust-ndarray/ndarray-linalg#128]
You code does not work on mac os

 = note: ld: library not found for -lgfortran                                                                                                                              
          clang: error: linker command failed with exit code 1 (use -v to see invocation)      

How do I resolve?  Or is this codebase no longer valid

**Comment by jturner314** [comment]
This is most likely an issue with the backend, not with `ndarray-linalg`. Are you using the `openblas` backend? If so, see [this page](https://github.com/blas-lapack-rs/blas-lapack-rs.github.io/wiki/Usage-on-macOS) in the docs for [`openblas-src`](https://github.com/blas-lapack-rs/openblas-src).

**Comment by termoshtt** [comment]
Please reopen if still unresolved!
