### ISSUE TITLE
Wrong parameter 10 in LAPACKE_sgesvd_work

### ISSUE THREAD

**Issue by joshgev** [rust-ndarray/ndarray-linalg#162]
Hi!

I am trying to use ndarray-linalg to compute the SVD of an Array2::<f32>.  My dependencies look like this:

```
[dependencies]
ndarray = { version = "0.12.1" , features = ["blas"] }
ndarray-linalg = { version = "0.11.1", features = ["openblas"]}
```

The program compiles and runs, but crashes my call to the `svd` function, which looks like this:

```
let (_, mut sv, vt) = centered.svd(false, true)?;
``` 

The crash yields this message:

```
Wrong parameter 10 in LAPACKE_sgesvd_work
```

As I typed up this issue, I thought I'd try `centered.svd(true, true)` and this _does_ work.  I am fine with needlessly computing the u matrix, but I thought I would still file this issue since it is not behavior I would expect given the interface, which allows the user to selectively enable/disable the computation of u and vt independently of one another.

**Comment by termoshtt** [comment]
Thanks reporting! I reproduce it.
