### ISSUE TITLE
New release with ndarray 0.13

### ISSUE THREAD

**Issue by jturner314** [rust-ndarray/ndarray-linalg#173]
@termoshtt Is there anything that needs to be done before releasing a new version?

**Comment by termoshtt** [comment]
I'd like to bump up rand to 0.7, but it will have compatibility issue around num-complex.
https://github.com/rust-ndarray/ndarray/issues/681

**Comment by termoshtt** [comment]
I created a working PR for rand 0.7 #176, but it seems to take long time :<
I will make a release 0.12.0 without rand 0.7.

**Comment by termoshtt** [comment]
0.12.0 has been released!

**Comment by jturner314** [comment]
Thanks!
