### ISSUE TITLE
Rust: problem using ndarray-linalg & ndarray crates

### ISSUE THREAD

**Issue by bashir-abdelwahed** [rust-ndarray/ndarray-linalg#271]
I am writing a cross compiled library in Rust (that will work on IOS/Android/Linux/MacOS). I am using [ndarray][1] to implement the algorithms.

I need to calculate the norm of an ArrayBase. I found [ndarray-linalg][2] which is a crate that implements lots of traits on ndarray's types.

But I am unable to use it:
```
// Cargo.toml
ndarray = { version = "0.15.1", default-features = true } 
ndarray-linalg = {version = "0.13.1"}

// src/main.rs
use ndarray::*;
use ndarray_linalg::*;

fn main() {
    let foo = ArrayBase::from(&[1,2,3]);
    foo.norm_l2(); // produces error
      //^^^^^^^ method not found in `&ArrayBase<OwnedRepr<f64>, Dim<[usize; 1]>>`
}
```

So here I have 2 questions:

 1. How to solve this problem and make these methods accessible in my program ?
 2. Is it a good idea to use these crates for compiling against android & IOS architectures anyway?

Thanks in advance.

  [1]: https://docs.rs/ndarray/0.15.1/ndarray/
  [2]: https://docs.rs/ndarray-linalg/0.13.1/ndarray_linalg/index.html

**Comment by jturner314** [comment]
`ndarray-linalg` hasn't been updated to`ndarray` 0.15 yet. Try changing your `Cargo.toml` to say `ndarray = { version = "0.14", default-features = true }`.
