### ISSUE TITLE
ndarray-linalg docs.rs failure to build

### ISSUE THREAD

**Issue by quietlychris** [rust-ndarray/ndarray-linalg#301]
Hello,

I was trying to review some of the documentation of `ndarray-linalg` today on docs.rs, but it looks like `0.14` has failed to build properly. I didn't see an open issue for it, so wasn't sure if anyone was aware. Thanks for all your work on this crate!

**Comment by jturner314** [comment]
Thanks for the heads up. It's weird – I'm not able to locally reproduce the issue docs.rs had. Based on the docs.rs build log, though, I've created #302 to hopefully fix it.

**Comment by termoshtt** [comment]
Thanks reporting. I've released  0.14.1 https://docs.rs/ndarray-linalg/0.14.1/ndarray_linalg/index.html with #302
