### ISSUE TITLE
static gfortran link

### ISSUE THREAD

**Issue by jianshu93** [rust-ndarray/ndarray-linalg#332]
Hello Team,

With openblas static feature, it can be linked statically but the gfortran itself was linked statically (gcc -lgfortran was required to link openblas), e.g, libgfortran.so.5 was actually linked to the binary if using ldd binary, together with libquadmath.so.0. I am wondering whether gfortran can be linked statically by gcc.

Thanks,

Jianshu

**Comment by termoshtt** [comment]
This should be an issue for openblas-src https://github.com/blas-lapack-rs/openblas-src/issues/88
