### ISSUE TITLE
Eigenvalue analysis for general matrices

### ISSUE THREAD

**Issue by termoshtt** [rust-ndarray/ndarray-linalg#40]
As argued in #29

**Comment by termoshtt** [comment]
transfer to #29

**Comment by J-F-Liu** [comment]
`impl_eigh!(f64, lapacke::dsyev);` is only for symmetric matrix, should use `lapacke::dgeev`.
And [Generalized Nonsymmetric Eigenvalue Problems](https://software.intel.com/en-us/onemkl-developer-reference-c-ggev#) are also nice to have.
